name: DB Deployment using goose
on:
   push: 
     branches: [main]
jobs:
  code-checkout:
    name: checkout from SCM
    uses: actions/checkout@v3
    with:
       repository: 
       path: 

  db-migration:
    runs-on: ubuntu-latest
    env:
           DBDRIVER: 
           DBSTRING: 
           FILENAME: 
           FILETYPE: 
           MIGRATEOPTIONS:  

    run:  
        - sh 'goose create $FILENAME $FILETYPE'
        - sh 'goose $DBDRIVER $DBSTRING status'
        - sh 'goose $DBDRIVER $DBSTRING $MIGRATEOPTIONS'
